### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by bitjockey42** [0x414A/emacs-config#1]
![emacs hypatia_001](https://cloud.githubusercontent.com/assets/6130766/13607375/78aaf1a4-e515-11e5-8c7e-e5cd3d4fd8d7.png)

**Comment by kalikoke** [comment]
<img width="828" alt="screen shot 2016-03-24 at 12 35 54 am" src="https://cloud.githubusercontent.com/assets/13822200/14009318/8d04803a-f158-11e5-9700-60903108ae7a.png">
